name: Build and test the debugger for linux

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Debug

jobs:

  build:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    name: Build and Test
    runs-on: ubuntu-latest
    
    defaults:
      run:
        shell: bash
        working-directory: scripts

    steps:
    - uses: actions/checkout@v3

    - name: update references
      run: |
        git submodule update --init --recursive

    - name: install vcpkg
      run: |
        chmod +x configVCPKG.sh
        ./configVCPKG.sh

    - name: Configure CMake
      # automatic create build folders
      run: cmake -S . --preset="debug-Makefiles"

    - name: Build
      # Build your program with the given configuration
      run: cmake --build . --preset="alDbg-debug-makefiles"

    #- name: Test
      #working-directory: ${{github.workspace}}/build
      # Execute tests defined by the CMake configuration.
      # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
      #run: ctest -C ${{env.BUILD_TYPE}}

